version: '3.7'

services:
  sv_nasm:
    # keeps the container running
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct_nasm
    volumes:
      - ./:/nasm
    command:
      - /bin/bash
