version: '3.7'


services:
  nasm:
    # keeps the container running
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasm
    volumes:
      - ./:/nasm
    command:
      - /bin/bash
