version: '3.7'

services:
  if-wu-nasm:
    tty: true
    build:
      context: .
      dockerfile: wu.Dockerfile
    container_name: cf-wu-nasm
    working_dir: /home/nasm
    volumes:
      - ./source:/home/nasm:z,rw

  if-no-nasm:
    tty: true
    build:
      context: .
      dockerfile: no.Dockerfile
    container_name: cf-no-nasm
    working_dir: /home/nasm
    volumes:
      - ./source:/home/nasm
