version: '3.7'

volumes:
  debian_nasm_codes:
    external: true

services:
  nasm_compiler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - debian_nasm_codes:/source:consistent
    command:
      - /bin/bash
